### ISSUE TITLE
related identifiers is broken

### ISSUE THREAD

**Issue by WardLT** [DLHub-Argonne/dlhub_sdk#171]
The function which sets related identifiers is broken. It should set the "relatedMetadataScheme" but does not.

```
Traceback (most recent call last):
  File "/home/lward/Work/JCESR/redox-webapp/servables/redox/publish_model.py", line 38, in <module>
    model.datacite.add_related_identifier("https://github.com/NREL/nfp", "URL", "Requires")
  File "/home/lward/miniconda3/envs/redoxweb/lib/python3.9/site-packages/dlhub_sdk/models/datacite.py", line 426, in add_related_identifier
    self.relatedIdentifiers.append(DataciteRelatedIdentifier(
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DataciteRelatedIdentifier
relatedMetadataScheme
  field required (type=value_error.missing)
```

**Comment by isaac-darling** [comment]
Sorry to be a unhelpful here, but I was unable to reproduce the error. I will note, however, that the code would seem to indicate that the field `relatedMetadataScheme` is an `Optional[str]` (reinforced by its type hint of `str | None`), and that the input of `relation_type` to `add_related_identifier()` is technically a `Union[str, DataciteRelationType]` but `"Requires"` is not in the `DataciteRelationType` `Enum`. These facts would seem to suggest an error on behalf on how `pydantic` is handled, but I am not certain where that occurs within the SDK---or even if it occurs within the state of the SDK I can see.
If the problem persists as such, I'm confident I can take care of it with some help in reproducing the error.
